IMAGE_NAME = debian
IMAGE_VERSION = stretch
IMAGE_VERSION_ALIASES =	9.0 9 latest
IMAGE_TITLE = Debian Stretch
IMAGE_DESCRIPTION = Debian Stretch
IMAGE_SOURCE_URL = https://github.com/scaleway/image-debian
IMAGE_VENDOR_URL = https://www.debian.org
IMAGE_BOOTSCRIPT = mainline 4.9
IMAGE_BASE_FLAVORS = common docker-based systemd feature-motd
