IMAGE_NAME = debian
IMAGE_VERSION = sid
IMAGE_VERSION_ALIASES = unstable
IMAGE_TITLE = Debian Sid/Unstable
IMAGE_DESCRIPTION = Debian Sid/Unstable
IMAGE_SOURCE_URL = https://github.com/scaleway/image-debian
IMAGE_VENDOR_URL = https://wiki.debian.org/DebianUnstable
IMAGE_BOOTSCRIPT = mainline 4.9
IMAGE_BASE_FLAVORS = common docker-based systemd feature-motd
